# Generated by Django 6.0.1 on 2026-01-15 15:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_role', models.CharField(max_length=20)),
                ('resume_ids', models.JSONField(default=list)),
                ('config_version', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('complete', 'Complete'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('results_ref', models.CharField(blank=True, max_length=500, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Analysis Run',
                'verbose_name_plural': 'Analysis Runs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobDescription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('raw_text', models.TextField()),
                ('structured_json', models.JSONField(default=dict)),
                ('requirements_required', models.JSONField(default=list)),
                ('requirements_preferred', models.JSONField(default=list)),
                ('responsibilities', models.JSONField(default=list)),
                ('skills_required', models.JSONField(default=list)),
                ('skills_preferred', models.JSONField(default=list)),
                ('min_years_experience', models.IntegerField(blank=True, null=True)),
                ('degree_requirements', models.CharField(blank=True, max_length=100, null=True)),
                ('salary_range', models.CharField(blank=True, max_length=100, null=True)),
                ('embedding_refs', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Job Description',
                'verbose_name_plural': 'Job Descriptions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MatchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_score', models.IntegerField()),
                ('semantic_similarity', models.IntegerField(default=0)),
                ('skills_match', models.IntegerField(default=0)),
                ('experience_seniority', models.IntegerField(default=0)),
                ('education_certs', models.IntegerField(default=0)),
                ('penalties', models.IntegerField(default=0)),
                ('required_skills_coverage_pct', models.FloatField(default=0)),
                ('preferred_skills_coverage_pct', models.FloatField(default=0)),
                ('relevant_years_estimate', models.FloatField(default=0)),
                ('title_level_match', models.CharField(blank=True, max_length=50, null=True)),
                ('evidence', models.JSONField(default=dict)),
                ('recommendations', models.JSONField(default=dict)),
                ('confidence', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Match Result',
                'verbose_name_plural': 'Match Results',
                'ordering': ['-overall_score'],
            },
        ),
        migrations.CreateModel(
            name='RecruiterBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization', models.CharField(blank=True, max_length=100, null=True)),
                ('resume_ids', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('uploading', 'Uploading'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed'), ('deleted', 'Deleted')], default='uploading', max_length=20)),
                ('processing_error', models.TextField(blank=True, null=True)),
                ('ttl_expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Recruiter Batch',
                'verbose_name_plural': 'Recruiter Batches',
                'ordering': ['-created_at'],
            },
        ),
    ]
