# Generated by Django 6.0.1 on 2026-01-15 15:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        ('resumes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisrun',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_descriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='analysisrun',
            name='job_description',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.jobdescription'),
        ),
        migrations.AddField(
            model_name='matchresult',
            name='analysis_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_results', to='jobs.analysisrun'),
        ),
        migrations.AddField(
            model_name='matchresult',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resumes.resumedocument'),
        ),
        migrations.AddField(
            model_name='recruiterbatch',
            name='job_description',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.jobdescription'),
        ),
        migrations.AddField(
            model_name='recruiterbatch',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='jobdescription',
            index=models.Index(fields=['owner'], name='jobs_jobdes_owner_i_468f81_idx'),
        ),
        migrations.AddIndex(
            model_name='analysisrun',
            index=models.Index(fields=['actor', 'status'], name='jobs_analys_actor_i_d43bc6_idx'),
        ),
        migrations.AddIndex(
            model_name='analysisrun',
            index=models.Index(fields=['job_description'], name='jobs_analys_job_des_e81384_idx'),
        ),
        migrations.AddIndex(
            model_name='matchresult',
            index=models.Index(fields=['analysis_run', 'overall_score'], name='jobs_matchr_analysi_382494_idx'),
        ),
        migrations.AddIndex(
            model_name='matchresult',
            index=models.Index(fields=['resume'], name='jobs_matchr_resume__2b8f74_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='matchresult',
            unique_together={('analysis_run', 'resume')},
        ),
        migrations.AddIndex(
            model_name='recruiterbatch',
            index=models.Index(fields=['owner', 'status'], name='jobs_recrui_owner_i_80e62f_idx'),
        ),
        migrations.AddIndex(
            model_name='recruiterbatch',
            index=models.Index(fields=['ttl_expires_at'], name='jobs_recrui_ttl_exp_288dae_idx'),
        ),
    ]
