# Generated by Django 6.0.1 on 2026-01-15 15:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParsedResume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extraction_method', models.CharField(choices=[('text_extract', 'Text Extract'), ('ocr_fallback', 'OCR Fallback')], max_length=20)),
                ('raw_text', models.TextField(blank=True, null=True)),
                ('structured_json', models.JSONField(default=dict)),
                ('section_index', models.JSONField(default=dict)),
                ('skills_normalized', models.JSONField(default=list)),
                ('titles_normalized', models.JSONField(default=list)),
                ('companies', models.JSONField(default=list)),
                ('employment_history', models.JSONField(default=list)),
                ('education', models.JSONField(default=list)),
                ('certifications', models.JSONField(default=list)),
                ('quality_flags', models.JSONField(default=dict)),
                ('embedding_refs', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Parsed Resume',
                'verbose_name_plural': 'Parsed Resumes',
            },
        ),
        migrations.CreateModel(
            name='ResumeChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_id', models.CharField(max_length=50)),
                ('section', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('start_offset', models.IntegerField()),
                ('end_offset', models.IntegerField()),
                ('page_number', models.IntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(default=dict)),
                ('embedding_vector', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Resume Chunk',
                'verbose_name_plural': 'Resume Chunks',
            },
        ),
        migrations.CreateModel(
            name='ResumeDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('talent_upload', 'Talent Upload'), ('recruiter_batch_upload', 'Recruiter Batch Upload')], max_length=30)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=10)),
                ('file_size_bytes', models.IntegerField()),
                ('checksum_hash', models.CharField(max_length=64)),
                ('storage_ref', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('parsing', 'Parsing'), ('parsed', 'Parsed'), ('failed', 'Failed'), ('deleted', 'Deleted')], default='uploaded', max_length=20)),
                ('parsing_error', models.TextField(blank=True, null=True)),
                ('ttl_expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Resume Document',
                'verbose_name_plural': 'Resume Documents',
                'ordering': ['-created_at'],
            },
        ),
    ]
