# Generated by Django 6.0.1 on 2026-01-15 15:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resumes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='resumedocument',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resumechunk',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='resumes.resumedocument'),
        ),
        migrations.AddField(
            model_name='parsedresume',
            name='resume',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parsed_data', to='resumes.resumedocument'),
        ),
        migrations.AddIndex(
            model_name='resumedocument',
            index=models.Index(fields=['owner', 'status'], name='resumes_res_owner_i_f2d2f4_idx'),
        ),
        migrations.AddIndex(
            model_name='resumedocument',
            index=models.Index(fields=['status'], name='resumes_res_status_a1c8e4_idx'),
        ),
        migrations.AddIndex(
            model_name='resumedocument',
            index=models.Index(fields=['ttl_expires_at'], name='resumes_res_ttl_exp_8b5d03_idx'),
        ),
        migrations.AddIndex(
            model_name='resumechunk',
            index=models.Index(fields=['resume', 'section'], name='resumes_res_resume__7927fe_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='resumechunk',
            unique_together={('resume', 'chunk_id')},
        ),
    ]
